// ROUTE DATA FILE
// This file is fetched fresh whenever Route Runner opens and internet is available.
// Edit coordinates, names, details or time ranges here, then redeploy to Netlify.
// Route Runner automatically reads time ranges from each location's detail text.
// It calculates expiry as 5 minutes before the latest ending time found in that detail.
// Example: 4pm–6pm expires at 5:55pm; 4pm–7pm expires at 6:55pm.
// If no readable time range is present in detail, that location will not auto-expire.
// The app records the successful fetch time on screen as 'Route data updated'.

const ROUTES = [
  {
    "id": "peak12-am",
    "name": "Peak 1 & 2 – Morning",
    "group": "Peak 1 & 2",
    "period": "Morning",
    "locations": [
      {
        "id": "peak12-am-01",
        "name": "Albert Street, Brisbane",
        "query": "Albert Street, Brisbane, Australia",
        "detail": "Bus Zone (B11) 6am–9am Monday–Friday between Mary Street & Margaret Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-am-02",
        "name": "Margaret Street, Brisbane",
        "query": "Margaret Street, Brisbane, Australia",
        "detail": "No Stopping (S11) & Clearway (C11) 7am–9am Monday–Friday between George Street & Albert Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-am-03",
        "name": "Mary Street, Brisbane",
        "query": "Mary Street, Brisbane, Australia",
        "detail": "Bus Zone (B11) 7am–10am Monday–Friday between Albert & George Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-am-04",
        "name": "Mary Street, Brisbane",
        "query": "Mary Street, Brisbane, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Edward Street & Market Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-am-05",
        "name": "George Street, Brisbane",
        "query": "George Street, Brisbane, Australia",
        "detail": "Clearway (C11), No Stopping (S11) & Bus Zone (B11) 7am–9am Monday–Friday – all of George Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-am-06",
        "name": "Elizabeth Street, Brisbane",
        "query": "Elizabeth Street, Brisbane, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday between George Street & Edward Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-am-07",
        "name": "Eagle Street, Brisbane",
        "query": "Eagle Street, Brisbane, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Market Street & Charlotte Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-am-08",
        "name": "Eagle Street, Brisbane",
        "query": "Eagle Street, Brisbane, Australia",
        "detail": "Bus Zone (B11) 7am–9am Monday–Friday between Elizabeth Street & Queen Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-am-09",
        "name": "Ann Street, Brisbane",
        "query": "Ann Street, Brisbane, Australia",
        "detail": "Clearway (C11) 7am–11am Monday–Friday; source notes right/left side conditions",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-am-10",
        "name": "Edward Street, Brisbane",
        "query": "Edward Street, Brisbane, Australia",
        "detail": "Clearway (C11) 7am–10am Monday–Friday between Ann Street & Adelaide Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-am-11",
        "name": "Adelaide Street, Brisbane",
        "query": "Adelaide Street, Brisbane, Australia",
        "detail": "Bus Zone (B11) & No Stopping (S11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      }
    ]
  },
  {
    "id": "peak12-pm",
    "name": "Peak 1 & 2 – Afternoon",
    "group": "Peak 1 & 2",
    "period": "Afternoon",
    "locations": [
      {
        "id": "peak12-pm-01",
        "name": "Ann Street, Brisbane",
        "query": "Ann Street, Brisbane, Australia",
        "detail": "Clearway (C11) 2pm–7pm Monday–Friday; source notes side-of-road conditions",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-pm-02",
        "name": "Edward Street, Brisbane",
        "query": "Edward Street, Brisbane, Australia",
        "detail": "Clearway (C11) 2pm–7pm Monday–Friday between Ann Street & Adelaide Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-pm-03",
        "name": "Mary Street, Brisbane",
        "query": "Mary Street, Brisbane, Australia",
        "detail": "Bus Zone (B11) 2pm–7pm Monday–Friday between Albert & George Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-pm-04",
        "name": "Charlotte Street, Brisbane",
        "query": "Charlotte Street, Brisbane, Australia",
        "detail": "Bus Zone (B11) 2pm–7pm Monday–Friday between Edward & Albert Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-pm-05",
        "name": "Margaret Street, Brisbane",
        "query": "Margaret Street, Brisbane, Australia",
        "detail": "Bus Zone (B11) 3pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-pm-06",
        "name": "George Street, Brisbane",
        "query": "George Street, Brisbane, Australia",
        "detail": "Bus Zone (B11) 3:30pm–7pm Monday–Friday between Margaret Street & Elizabeth Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-pm-07",
        "name": "Edward Street, Brisbane",
        "query": "Edward Street, Brisbane, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-pm-08",
        "name": "Alice Street, Brisbane",
        "query": "Alice Street, Brisbane, Australia",
        "detail": "Clearway (C11) & Bus Zone (B11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-pm-09",
        "name": "George Street, Brisbane",
        "query": "George Street, Brisbane, Australia",
        "detail": "Clearway (C11) & Bus Zone (B11) 4pm–7pm Monday–Friday – all of George Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-pm-10",
        "name": "Elizabeth Street, Brisbane",
        "query": "Elizabeth Street, Brisbane, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-pm-11",
        "name": "Charlotte Street, Brisbane",
        "query": "Charlotte Street, Brisbane, Australia",
        "detail": "Bus Zone (B11) 4pm–7pm Monday–Friday between Eagle Street & Market Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-pm-12",
        "name": "Mary Street, Brisbane",
        "query": "Mary Street, Brisbane, Australia",
        "detail": "Bus Zone (B11) 4pm–6pm Monday–Friday between Edward Street & Market Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-pm-13",
        "name": "Adelaide Street, Brisbane",
        "query": "Adelaide Street, Brisbane, Australia",
        "detail": "Bus Zone (B11) & No Stopping (S11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-pm-14",
        "name": "Creek Street, Brisbane",
        "query": "Creek Street, Brisbane, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      }
    ]
  },
  {
    "id": "peak3-am",
    "name": "Peak 3 – Morning",
    "group": "Peak 3",
    "period": "Morning",
    "locations": [
      {
        "id": "peak3-am-01",
        "name": "Sylvan Road, Toowong",
        "query": "Sylvan Road, Toowong QLD, Australia",
        "detail": "No Stopping (S11) 6am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak3-am-02",
        "name": "Herschel Street, Brisbane",
        "query": "Herschel Street, Brisbane, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak3-am-03",
        "name": "Petrie Terrace, Petrie Terrace",
        "query": "Petrie Terrace, Petrie Terrace QLD, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak3-am-04",
        "name": "Caxton Street, Petrie Terrace",
        "query": "Caxton Street, Petrie Terrace QLD, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak3-am-05",
        "name": "Given Terrace, Paddington",
        "query": "Given Terrace, Paddington QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Great George Street & Princess Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak3-am-06",
        "name": "Baroona Road, Milton",
        "query": "Baroona Road, Milton QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Beck Street & Milton Road",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak3-am-07",
        "name": "Park Road, Milton",
        "query": "Park Road, Milton QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      }
    ]
  },
  {
    "id": "peak3-pm",
    "name": "Peak 3 – Afternoon",
    "group": "Peak 3",
    "period": "Afternoon",
    "locations": [
      {
        "id": "peak3-pm-01",
        "name": "Park Road, Milton",
        "query": "Park Road, Milton QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak3-pm-02",
        "name": "Baroona Road, Milton",
        "query": "Baroona Road, Milton QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday between Milton Road & Haig Road",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak3-pm-03",
        "name": "Given Terrace, Paddington",
        "query": "Given Terrace, Paddington QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday between Campbell Street & Latrobe Terrace",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak3-pm-04",
        "name": "Latrobe Terrace, Paddington",
        "query": "Latrobe Terrace, Paddington QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday between Given Terrace & Gladstone Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak3-pm-05",
        "name": "Caxton Street, Petrie Terrace",
        "query": "Caxton Street, Petrie Terrace QLD, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak3-pm-06",
        "name": "Petrie Terrace, Petrie Terrace",
        "query": "Petrie Terrace, Petrie Terrace QLD, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak3-pm-07",
        "name": "North Quay, Brisbane",
        "query": "North Quay, Brisbane, Australia",
        "detail": "Bus Zone (B11) 4pm–7pm between Saul Street & Makerston Street",
        "lat": null,
        "lng": null,
      }
    ]
  },
  {
    "id": "peak4-am",
    "name": "Peak 4 – Morning",
    "group": "Peak 4",
    "period": "Morning",
    "locations": [
      {
        "id": "peak4-am-01",
        "name": "Saint Pauls Terrace, Fortitude Valley / Spring Hill",
        "query": "Saint Pauls Terrace, Fortitude Valley QLD, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-am-02",
        "name": "Boundary Street, Spring Hill",
        "query": "Boundary Street, Spring Hill QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Water Street & Saint Pauls Terrace",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-am-03",
        "name": "Little Edward Street, Spring Hill",
        "query": "Little Edward Street, Spring Hill QLD, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-am-04",
        "name": "Upper Edward Street, Spring Hill",
        "query": "Upper Edward Street, Spring Hill QLD, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-am-05",
        "name": "Turbot Street, Spring Hill / Brisbane",
        "query": "Turbot Street, Brisbane, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-am-06",
        "name": "Wharf Street, Spring Hill / Brisbane",
        "query": "Wharf Street, Brisbane, Australia",
        "detail": "Clearway (C11) & No Stopping (S11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-am-07",
        "name": "Macrossan Street, Brisbane",
        "query": "Macrossan Street, Brisbane, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-am-08",
        "name": "Adelaide Street, Brisbane",
        "query": "Adelaide Street, Brisbane, Australia",
        "detail": "Clearway (C11) & No Stopping (S11) 7am–9am Monday–Friday between Wharf Street & Boundary Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-am-09",
        "name": "Ann Street, Brisbane",
        "query": "Ann Street, Brisbane, Australia",
        "detail": "Clearway (C11) 7am–11am Monday–Friday; source notes right/left side conditions",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-am-10",
        "name": "Leichhardt Street, Spring Hill",
        "query": "Leichhardt Street, Spring Hill QLD, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday between North Street & Little Edward Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-am-11",
        "name": "Wickham Terrace, Spring Hill",
        "query": "Wickham Terrace, Spring Hill QLD, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday between Gregory Terrace & North Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-am-12",
        "name": "Gregory Terrace, Spring Hill",
        "query": "Gregory Terrace, Spring Hill QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Brunswick Street & Warry Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-am-13",
        "name": "Gotha Street, Fortitude Valley",
        "query": "Gotha Street, Fortitude Valley QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Barry Parade & Wickham Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-am-14",
        "name": "Water Street, Spring Hill",
        "query": "Water Street, Spring Hill QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday before Boundary Street intersection",
        "lat": null,
        "lng": null,
      }
    ]
  },
  {
    "id": "peak4-pm",
    "name": "Peak 4 – Afternoon",
    "group": "Peak 4",
    "period": "Afternoon",
    "locations": [
      {
        "id": "peak4-pm-01",
        "name": "Ann Street, Brisbane",
        "query": "Ann Street, Brisbane, Australia",
        "detail": "Clearway (C11) 2pm–7pm Monday–Friday; source notes side-of-road conditions between Queen Street & Creek Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-pm-02",
        "name": "Boundary Street, Spring Hill",
        "query": "Boundary Street, Spring Hill QLD, Australia",
        "detail": "No Stopping (S11) 2pm–6pm Monday–Friday between Milne Street & Gregory Terrace",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-pm-03",
        "name": "Saint Pauls Terrace, Fortitude Valley / Spring Hill",
        "query": "Saint Pauls Terrace, Fortitude Valley QLD, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-pm-04",
        "name": "Boundary Street, Spring Hill",
        "query": "Boundary Street, Spring Hill QLD, Australia",
        "detail": "No Stopping (S11) 4pm–6pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-pm-05",
        "name": "Little Edward Street, Spring Hill",
        "query": "Little Edward Street, Spring Hill QLD, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-pm-06",
        "name": "Upper Edward Street, Spring Hill",
        "query": "Upper Edward Street, Spring Hill QLD, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-pm-07",
        "name": "Turbot Street, Spring Hill / Brisbane",
        "query": "Turbot Street, Brisbane, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-pm-08",
        "name": "Wharf Street, Spring Hill / Brisbane",
        "query": "Wharf Street, Brisbane, Australia",
        "detail": "Clearway (C11) & No Stopping (S11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-pm-09",
        "name": "Macrossan Street, Brisbane",
        "query": "Macrossan Street, Brisbane, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-pm-10",
        "name": "Adelaide Street, Brisbane",
        "query": "Adelaide Street, Brisbane, Australia",
        "detail": "Clearway (C11) & No Stopping (S11) 4pm–7pm Monday–Friday between Wharf Street & Boundary Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-pm-11",
        "name": "Leichhardt Street, Spring Hill",
        "query": "Leichhardt Street, Spring Hill QLD, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday between Little Edward Street & Wickham Terrace",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-pm-12",
        "name": "Wickham Terrace, Spring Hill",
        "query": "Wickham Terrace, Spring Hill QLD, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday between Leichhardt Street & Parkland Blvd",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak4-pm-13",
        "name": "Gregory Terrace, Spring Hill",
        "query": "Gregory Terrace, Spring Hill QLD, Australia",
        "detail": "No Stopping (S11) 4pm–6pm Monday–Friday between Brunswick Street & Warry Street",
        "lat": null,
        "lng": null,
      }
    ]
  },
  {
    "id": "peak5-am",
    "name": "Peak 5 – Morning",
    "group": "Peak 5",
    "period": "Morning",
    "locations": [
      {
        "id": "peak5-am-01",
        "name": "Wickham Street, Fortitude Valley",
        "query": "Wickham Street, Fortitude Valley QLD, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-am-02",
        "name": "Constance Street, Fortitude Valley",
        "query": "Constance Street, Fortitude Valley QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Wickham Street & Ann Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-am-03",
        "name": "McLachlan Street, Fortitude Valley",
        "query": "McLachlan Street, Fortitude Valley QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Connor Street & James Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-am-04",
        "name": "Brookes Street, Fortitude Valley / Bowen Hills",
        "query": "Brookes Street, Bowen Hills QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-am-05",
        "name": "O'Connell Terrace, Bowen Hills",
        "query": "O'Connell Terrace, Bowen Hills QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-am-06",
        "name": "Abbortsford Road, Bowen Hills",
        "query": "Abbortsford Road, Bowen Hills QLD, Australia",
        "detail": "No Stopping (S11) & Clearway (C11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-am-07",
        "name": "Edmondstone Road, Bowen Hills",
        "query": "Edmondstone Road, Bowen Hills QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday before Abbortsford Road intersection",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-am-08",
        "name": "Montplier Road, Bowen Hills",
        "query": "Montplier Road, Bowen Hills QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Down Street & Dukinfield Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-am-09",
        "name": "Brunswick Street, Fortitude Valley / New Farm",
        "query": "Brunswick Street, Fortitude Valley QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Barker Street & Malt Street",
        "lat": null,
        "lng": null,
      }
    ]
  },
  {
    "id": "peak5-pm",
    "name": "Peak 5 – Afternoon",
    "group": "Peak 5",
    "period": "Afternoon",
    "locations": [
      {
        "id": "peak5-pm-01",
        "name": "Wickham Street, Fortitude Valley",
        "query": "Wickham Street, Fortitude Valley QLD, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-pm-02",
        "name": "Constance Street, Fortitude Valley",
        "query": "Constance Street, Fortitude Valley QLD, Australia",
        "detail": "No Stopping (S11) 4pm–6pm Monday–Friday between Wickham Street & Ann Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-pm-03",
        "name": "McLachlan Street, Fortitude Valley",
        "query": "McLachlan Street, Fortitude Valley QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday between Connor Street & James Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-pm-04",
        "name": "Brookes Street, Fortitude Valley / Bowen Hills",
        "query": "Brookes Street, Bowen Hills QLD, Australia",
        "detail": "No Stopping (S11) 4pm–6pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-pm-05",
        "name": "O'Connell Terrace, Bowen Hills",
        "query": "O'Connell Terrace, Bowen Hills QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-pm-06",
        "name": "Abbortsford Road, Bowen Hills",
        "query": "Abbortsford Road, Bowen Hills QLD, Australia",
        "detail": "Inbound No Stopping (S11) 4pm–6pm; outbound Clearway (C11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-pm-07",
        "name": "Edmondstone Road, Bowen Hills",
        "query": "Edmondstone Road, Bowen Hills QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday before Abbortsford Road intersection",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-pm-08",
        "name": "Montplier Road, Bowen Hills",
        "query": "Montplier Road, Bowen Hills QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday between Down Street & Dukinfield Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-pm-09",
        "name": "Brunswick Street, Fortitude Valley / New Farm",
        "query": "Brunswick Street, Fortitude Valley QLD, Australia",
        "detail": "No Stopping (S11) 4pm–6pm Monday–Friday between Arthur Street & Annie Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-pm-10",
        "name": "Warner Street, Fortitude Valley",
        "query": "Warner Street, Fortitude Valley QLD, Australia",
        "detail": "Bus Zone (B11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-pm-11",
        "name": "Commercial Road, Newstead",
        "query": "Commercial Road, Newstead QLD, Australia",
        "detail": "No Stopping (S11) 4pm–6pm Monday–Friday between Leopold Street & Ann Street",
        "lat": null,
        "lng": null,
      }
    ]
  },
  {
    "id": "peak6-am",
    "name": "Peak 6 – Morning",
    "group": "Peak 6",
    "period": "Morning",
    "locations": [
      {
        "id": "peak6-am-01",
        "name": "Cordelia Street, South Brisbane",
        "query": "Cordelia Street, South Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak6-am-02",
        "name": "Marivale Street, South Brisbane",
        "query": "Marivale Street, South Brisbane QLD, Australia",
        "detail": "No Stopping (S11) & Clearway (C11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak6-am-03",
        "name": "Glenelg Street, South Brisbane",
        "query": "Glenelg Street, South Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak6-am-04",
        "name": "Montegue Road, South Brisbane",
        "query": "Montegue Road, South Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Beesley Street & Jane Street",
        "lat": null,
        "lng": null,
      }
    ]
  },
  {
    "id": "peak6-pm",
    "name": "Peak 6 – Afternoon",
    "group": "Peak 6",
    "period": "Afternoon",
    "locations": [
      {
        "id": "peak6-pm-01",
        "name": "Cordelia Street, South Brisbane",
        "query": "Cordelia Street, South Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm between Vulture Street & Ernest Street; 4pm–6pm between Melbourne Street & Peel Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak6-pm-02",
        "name": "Marivale Street, South Brisbane",
        "query": "Marivale Street, South Brisbane QLD, Australia",
        "detail": "No Stopping / Clearway conditions vary by segment between Montegue Road, Peel Street, Melbourne Street & Glenelg Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak6-pm-03",
        "name": "Glenelg Street, South Brisbane",
        "query": "Glenelg Street, South Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak6-pm-04",
        "name": "Montegue Road, South Brisbane",
        "query": "Montegue Road, South Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 4pm–6pm Monday–Friday between Beesley Street & Jane Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak6-pm-05",
        "name": "Fleet Lane, South Brisbane",
        "query": "Fleet Lane, South Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 4pm–6pm Monday–Friday",
        "lat": null,
        "lng": null,
      }
    ]
  },
  {
    "id": "peak7-am",
    "name": "Peak 7 – Morning",
    "group": "Peak 7",
    "period": "Morning",
    "locations": [
      {
        "id": "peak7-am-01",
        "name": "Stanley Street, East Brisbane",
        "query": "Stanley Street, East Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 6am–9am Monday–Friday between Norman Street & Wellington Road",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak7-am-02",
        "name": "Annerley Road, Woolloongabba / South Brisbane",
        "query": "Annerley Road, Woolloongabba QLD, Australia",
        "detail": "No Stopping (S11) 6am–9am Monday–Friday between Stephens Road & Stanley Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak7-am-03",
        "name": "Ipswich Road, Woolloongabba",
        "query": "Ipswich Road, Woolloongabba QLD, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday between Stanley Street & Balaclava Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak7-am-04",
        "name": "Balaclava Street, Woolloongabba",
        "query": "Balaclava Street, Woolloongabba QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak7-am-05",
        "name": "Logan Road, Woolloongabba",
        "query": "Logan Road, Woolloongabba QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Qualtrough Street & Balaclava Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak7-am-06",
        "name": "Wellington Road, East Brisbane",
        "query": "Wellington Road, East Brisbane QLD, Australia",
        "detail": "Clearway (C11) 7am–10am Monday–Friday between Vulture Street & Shafston Avenue",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak7-am-07",
        "name": "Okeefe Street, Woolloongabba",
        "query": "Okeefe Street, Woolloongabba QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday after Ipswich Road intersection",
        "lat": null,
        "lng": null,
      }
    ]
  },
  {
    "id": "peak7-pm",
    "name": "Peak 7 – Afternoon",
    "group": "Peak 7",
    "period": "Afternoon",
    "locations": [
      {
        "id": "peak7-pm-01",
        "name": "Annerley Road, Woolloongabba / South Brisbane",
        "query": "Annerley Road, Woolloongabba QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday between Stephens Road & Stanley Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak7-pm-02",
        "name": "Vulture Street, South Brisbane",
        "query": "Vulture Street, South Brisbane QLD, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday between Dock Street & Leopard Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak7-pm-03",
        "name": "Ipswich Road, Woolloongabba",
        "query": "Ipswich Road, Woolloongabba QLD, Australia",
        "detail": "Clearway (C11) 4pm–6pm Monday–Friday between Stanley Street & Balaclava Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak7-pm-04",
        "name": "Balaclava Street, Woolloongabba",
        "query": "Balaclava Street, Woolloongabba QLD, Australia",
        "detail": "No Stopping (S11) 4pm–6pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak7-pm-05",
        "name": "Logan Road, Woolloongabba",
        "query": "Logan Road, Woolloongabba QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday between Lotus Street & Deshon Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak7-pm-06",
        "name": "Overend Street, East Brisbane",
        "query": "Overend Street, East Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 4pm–6pm between Lisburn Street & Hampton Street; 4pm–7pm between Hampton Street & Wellington Road",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak7-pm-07",
        "name": "Wellington Road, East Brisbane",
        "query": "Wellington Road, East Brisbane QLD, Australia",
        "detail": "No Stopping 4pm–6pm between Overend Street & Logan Road; Clearway 4pm–7pm between Waterloo Street & Lytton Road",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak7-pm-08",
        "name": "Water Street, South Brisbane",
        "query": "Water Street, South Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak7-pm-09",
        "name": "Okeefe Street, Woolloongabba",
        "query": "Okeefe Street, Woolloongabba QLD, Australia",
        "detail": "No Stopping (S11) 3pm–7pm Monday–Friday after Ipswich Road intersection",
        "lat": null,
        "lng": null,
      }
    ]
  }
];
