// ROUTE DATA FILE
// This file is fetched fresh whenever Route Runner opens and internet is available.
// Edit coordinates, names, details or time ranges here, then redeploy to Netlify.
// Route Runner automatically reads time ranges from each location's detail text.
// It calculates expiry as 5 minutes before the latest ending time found in that detail.
// Example: 4pm–6pm expires at 5:55pm; 4pm–7pm expires at 6:55pm.
// If no readable time range is present in detail, that location will not auto-expire.
// The app records the successful fetch time on screen as 'Route data updated'.
// Each location has an "order" number for Recommended sort (lower = earlier).
// Changing id does not change order. Two stops can share a number; file order breaks the tie.
// Leave order null/missing to put a stop after all numbered stops.

const ROUTES = [
  {
    "id": "peak12-am",
    "name": "Peak 1 & 2 – Morning",
    "group": "Peak 1 & 2",
    "period": "Morning",
    "locations": [
      {
        "id": "peak12-am-01",
        "order": 1,
        "name": "Albert Street, Brisbane",
        "query": "Albert Street, Brisbane, Australia",
        "detail": "Bus Zone (B11) 6am–9am Monday–Friday between Mary Street & Margaret Street",
        "lat": -27.472042,
        "lng": 153.027620,
      },
      {
        "id": "peak12-am-02",
        "order": 2,
        "name": "Margaret Street, Brisbane",
        "query": "Margaret Street, Brisbane, Australia",
        "detail": "No Stopping (S11) & Clearway (C11) 7am–9am Monday–Friday between George Street & Albert Street",
        "lat": -27.472626,
        "lng": 153.028322,
      },
      {
        "id": "peak12-am-03",
        "order": 3,
        "name": "Mary Street, Brisbane",
        "query": "Mary Street, Brisbane, Australia",
        "detail": "Bus Zone (B11) 7am–10am Monday–Friday between Albert & George Street",
        "lat": -27.472314,
        "lng": 153.027003,
      },
      {
        "id": "peak12-am-04",
        "order": 4,
        "name": "Mary Street, Brisbane",
        "query": "Mary Street, Brisbane, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Edward Street & Market Street",
        "lat": -27.470481,
        "lng": 153.029289,
      },
      {
        "id": "peak12-am-05",
        "order": 5,
        "name": "George Street, Brisbane",
        "query": "George Street, Brisbane, Australia",
        "detail": "Clearway (C11), No Stopping (S11) & Bus Zone (B11) 7am–9am Monday–Friday – all of George Street",
        "lat": -27.473858,
        "lng": 153.026376,
      },
      {
        "id": "peak12-am-06",
        "order": 6,
        "name": "Elizabeth Street, Brisbane",
        "query": "Elizabeth Street, Brisbane, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday between George Street & Edward Street",
        "lat": -27.471589,
        "lng": 153.024443,
      },
      {
        "id": "peak12-am-07",
        "order": 7,
        "name": "Eagle Street, Brisbane",
        "query": "Eagle Street, Brisbane, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Market Street & Charlotte Street",
        "lat": -27.469429,
        "lng": 153.030206,
      },
      {
        "id": "peak12-am-08",
        "order": 8,
        "name": "Eagle Street, Brisbane",
        "query": "Eagle Street, Brisbane, Australia",
        "detail": "Bus Zone (B11) 7am–9am Monday–Friday between Elizabeth Street & Queen Street",
        "lat": -27.467610,
        "lng": 153.029515,
      },
      {
        "id": "peak12-am-09",
        "order": 9,
        "name": "Ann Street, Brisbane",
        "query": "Ann Street, Brisbane, Australia",
        "detail": "Clearway (C11) 7am–11am Monday–Friday (RIGHT); 7am–11am Monday–Saturday (LEFT)",
        "lat": -27.462473,
        "lng": 153.031052,
      },
      {
        "id": "peak12-am-10",
        "order": 10,
        "name": "Edward Street, Brisbane",
        "query": "Edward Street, Brisbane, Australia",
        "detail": "Clearway (C11) 7am–10am Monday–Friday between Ann Street & Adelaide Street",
        "lat": -27.466913,
        "lng": 153.025545,
      },
      {
        "id": "peak12-am-11",
        "order": 11,
        "name": "Adelaide Street, Brisbane",
        "query": "Adelaide Street, Brisbane, Australia",
        "detail": "Bus Zone (B11) & No Stopping (S11) 7am–9am Monday–Friday",
        "lat": -27.466658,
        "lng": 153.027274,
      }
    ]
  },
  {
    "id": "peak12-pm",
    "name": "Peak 1 & 2 – Afternoon",
    "group": "Peak 1 & 2",
    "period": "Afternoon",
    "locations": [
      {
        "id": "peak12-pm-01",
        "order": 1,
        "name": "Ann Street, Brisbane",
        "query": "Ann Street, Brisbane, Australia",
        "detail": "Clearway (C11) 2pm–7pm Monday–Friday (RIGHT); 2pm–7pm Monday–Saturday (LEFT)",
        "lat": -27.462473,
        "lng": 153.031052,
      },
      {
        "id": "peak12-pm-02",
        "order": 2,
        "name": "Edward Street, Brisbane",
        "query": "Edward Street, Brisbane, Australia",
        "detail": "Clearway (C11) 2pm–7pm Monday–Friday between Ann Street & Adelaide Street",
        "lat": -27.466913,
        "lng": 153.025545,
      },
      {
        "id": "peak12-pm-03",
        "order": 3,
        "name": "Mary Street, Brisbane",
        "query": "Mary Street, Brisbane, Australia",
        "detail": "Bus Zone (B11) 2pm–7pm Monday–Friday between Albert & George Street",
        "lat": -27.472314,
        "lng": 153.027003,
      },
      {
        "id": "peak12-pm-04",
        "order": 4,
        "name": "Charlotte Street, Brisbane",
        "query": "Charlotte Street, Brisbane, Australia",
        "detail": "Bus Zone (B11) 3pm–7pm Monday–Friday between Edward & Albert Street",
        "lat": -27.470464,
        "lng": 153.027657,
      },
      {
        "id": "peak12-pm-05",
        "order": 5,
        "name": "Margaret Street, Brisbane",
        "query": "Margaret Street, Brisbane, Australia",
        "detail": "Bus Zone (B11) 3pm–7pm Monday–Friday",
        "lat": -27.472626,
        "lng": 153.028322,
      },
      {
        "id": "peak12-pm-06",
        "order": 6,
        "name": "George Street, Brisbane",
        "query": "George Street, Brisbane, Australia",
        "detail": "Bus Zone (B11) 3:30pm–7pm Monday–Friday between Margaret Street & Elizabeth Street",
        "lat": -27.473858,
        "lng": 153.026376,
      },
      {
        "id": "peak12-pm-07",
        "order": 7,
        "name": "Edward Street, Brisbane",
        "query": "Edward Street, Brisbane, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak12-pm-08",
        "order": 8,
        "name": "Alice Street, Brisbane",
        "query": "Alice Street, Brisbane, Australia",
        "detail": "Clearway (C11) & Bus Zone (B11) 4pm–7pm Monday–Friday",
        "lat": -27.472233,
        "lng": 153.030520,
      },
      {
        "id": "peak12-pm-09",
        "order": 9,
        "name": "George Street, Brisbane",
        "query": "George Street, Brisbane, Australia",
        "detail": "Clearway (C11) & Bus Zone (B11) 4pm–7pm Monday–Friday – all of George Street",
        "lat": -27.473858,
        "lng": 153.026376,
      },
      {
        "id": "peak12-pm-10",
        "order": 10,
        "name": "Elizabeth Street, Brisbane",
        "query": "Elizabeth Street, Brisbane, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday",
        "lat": -27.470307,
        "lng": 153.026078,
      },   {
        "id": "peak12-pm-11",
        "order": 11,
        "name": "Elizabeth Street, Brisbane",
        "query": "Elizabeth Street, Brisbane, Australia",
        "detail": "Bus Zone (B11) 2:30pm–7pm Monday–Friday",
        "lat": -27.471589,
        "lng": 153.024443,
      },
      {
        "id": "peak12-pm-12",
        "order": 12,
        "name": "Charlotte Street, Brisbane",
        "query": "Charlotte Street, Brisbane, Australia",
        "detail": "Bus Zone (B11) 3pm–7pm Monday–Friday between Eagle Street & Market Street",
        "lat": -27.468605,
        "lng": 153.030050,
      },
      {
        "id": "peak12-pm-13",
        "order": 13,
        "name": "Mary Street, Brisbane",
        "query": "Mary Street, Brisbane, Australia",
        "detail": "Bus Zone (B11) 4pm–6pm Monday–Friday between Edward Street & Market Street",
        "lat": -27.470481,
        "lng": 153.029289,
      },
      {
        "id": "peak12-pm-14",
        "order": 14,
        "name": "Adelaide Street, Brisbane",
        "query": "Adelaide Street, Brisbane, Australia",
        "detail": "Bus Zone (B11) & No Stopping (S11) 4pm–7pm Monday–Friday",
        "lat": -27.466658,
        "lng": 153.027274,
      },
      {
        "id": "peak12-pm-15",
        "order": 15,
        "name": "Creek Street, Brisbane",
        "query": "Creek Street, Brisbane, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday",
        "lat": -27.466364,
        "lng": 153.027932,
      }
    ]
  },
  {
    "id": "peak3-am",
    "name": "Peak 3 – Morning",
    "group": "Peak 3",
    "period": "Morning",
    "locations": [
      {
        "id": "peak3-am-01",
        "order": 1,
        "name": "Sylvan Road, Toowong",
        "query": "Sylvan Road, Toowong QLD, Australia",
        "detail": "No Stopping (S11) 6am–9am Monday–Friday",
        "lat": -27.478900,
        "lng": 152.986355,
      },
      {
        "id": "peak3-am-02",
        "order": 2,
        "name": "Herschel Street, Brisbane",
        "query": "Herschel Street, Brisbane, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday",
        "lat": -27.468175,
        "lng": 153.018562,
      },
      {
        "id": "peak3-am-03",
        "order": 3,
        "name": "Petrie Terrace, Petrie Terrace",
        "query": "Petrie Terrace, Petrie Terrace QLD, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday",
        "lat": -27.464415,
        "lng": 153.013930,
      },
      {
        "id": "peak3-am-04",
        "order": 4,
        "name": "Caxton Street, Petrie Terrace",
        "query": "Caxton Street, Petrie Terrace QLD, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday",
        "lat": -27.462387,
        "lng": 153.009097,
      },
      {
        "id": "peak3-am-05",
        "order": 5,
        "name": "Given Terrace, Paddington",
        "query": "Given Terrace, Paddington QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Great George Street & Princess Street",
        "lat": -27.461217,
        "lng": 153.004739,
      },
      {
        "id": "peak3-am-06",
        "order": 6,
        "name": "Baroona Road, Milton",
        "query": "Baroona Road, Milton QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Beck Street & Milton Road",
        "lat": -27.466205,
        "lng": 153.000109,
      },
      {
        "id": "peak3-am-07",
        "order": 7,
        "name": "Park Road, Milton",
        "query": "Park Road, Milton QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday",
        "lat": -27.470044,
        "lng": 153.004320,
      }
    ]
  },
  {
    "id": "peak3-pm",
    "name": "Peak 3 – Afternoon",
    "group": "Peak 3",
    "period": "Afternoon",
    "locations": [
      {
        "id": "peak3-pm-01",
        "order": 1,
        "name": "Park Road, Milton",
        "query": "Park Road, Milton QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday",
        "lat": -27.471556,
        "lng": 153.004869,
      },
      {
        "id": "peak3-pm-02",
        "order": 2,
        "name": "Baroona Road, Milton",
        "query": "Baroona Road, Milton QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday between Milton Road & Haig Road",
        "lat": -27.468279,
        "lng": 153.002620,
      },
      {
        "id": "peak3-pm-03",
        "order": 3,
        "name": "Given Terrace, Paddington",
        "query": "Given Terrace, Paddington QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday between Campbell Street & Latrobe Terrace",
        "lat": -27.462122,
        "lng": 153.007323,
      },
      {
        "id": "peak3-pm-04",
        "order": 4,
        "name": "Latrobe Terrace, Paddington",
        "query": "Latrobe Terrace, Paddington QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday between Given Terrace & Gladstone Street",
        "lat": -27.460101,
        "lng": 153.002089,
      },
      {
        "id": "peak3-pm-05",
        "order": 5,
        "name": "Caxton Street, Petrie Terrace",
        "query": "Caxton Street, Petrie Terrace QLD, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday",
        "lat": -27.464319,
        "lng": 153.012594,
      },
      {
        "id": "peak3-pm-06",
        "order": 6,
        "name": "Petrie Terrace, Petrie Terrace",
        "query": "Petrie Terrace, Petrie Terrace QLD, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday",
        "lat": -27.464415,
        "lng": 153.013930,
      },
      {
        "id": "peak3-pm-07",
        "order": 7,
        "name": "North Quay, Brisbane",
        "query": "North Quay, Brisbane, Australia",
        "detail": "Bus Zone (B11) 4pm–7pm between Saul Street & Makerston Street",
        "lat": -27.467237,
        "lng": 153.016364,
      }
    ]
  },
  {
    "id": "peak4-am",
    "name": "Peak 4 – Morning",
    "group": "Peak 4",
    "period": "Morning",
    "locations": [
      {
        "id": "peak4-am-01",
        "order": 1,
        "name": "Saint Pauls Terrace, Fortitude Valley / Spring Hill",
        "query": "Saint Pauls Terrace, Fortitude Valley QLD, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday both directions",
        "lat": -27.451965,
        "lng": 153.035799,
      },
      {
        "id": "peak4-am-02",
        "order": 2,
        "name": "Boundary Street, Spring Hill",
        "query": "Boundary Street, Spring Hill QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Water Street & Saint Pauls Terrace",
        "lat": -27.460867,
        "lng": 153.024896,
      },
      {
        "id": "peak4-am-03",
        "order": 3,
        "name": "Little Edward Street, Spring Hill",
        "query": "Little Edward Street, Spring Hill QLD, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday",
        "lat": -27.461042,
        "lng": 153.024473,
      },
      {
        "id": "peak4-am-04",
        "order": 4,
        "name": "Upper Edward Street, Spring Hill",
        "query": "Upper Edward Street, Spring Hill QLD, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday both directions",
        "lat": -27.463022,
        "lng": 153.024388,
      },
      {
        "id": "peak4-am-05",
        "order": 5,
        "name": "Turbot Street, Spring Hill / Brisbane",
        "query": "Turbot Street, Brisbane, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday",
        "lat": -27.467324,
        "lng": 153.023095,
      },
      {
        "id": "peak4-am-06",
        "order": 6,
        "name": "Wharf Street, Spring Hill / Brisbane",
        "query": "Wharf Street, Brisbane, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday",
        "lat": -27.462028,
        "lng": 153.026768,
      },{
        "id": "peak4-am-07",
        "order": 7,
        "name": "Wharf Street, Spring Hill / Brisbane",
        "query": "Wharf Street, Brisbane, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday",
        "lat": -27.464494,
        "lng": 153.029182,
      },
      {
        "id": "peak4-am-08",
        "order": 8,
        "name": "Macrossan Street, Brisbane",
        "query": "Macrossan Street, Brisbane, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday",
        "lat": -27.462891,
        "lng": 153.032395,
      },
      {
        "id": "peak4-am-09",
        "order": 9,
        "name": "Adelaide Street, Brisbane",
        "query": "Adelaide Street, Brisbane, Australia",
        "detail": "Clearway (C11) & No Stopping (S11) 7am–9am Monday–Friday between Wharf Street & Boundary Street",
        "lat": -27.462893,
        "lng": 153.031893,
      },
      {
        "id": "peak4-am-10",
        "order": 10,
        "name": "Ann Street, Brisbane",
        "query": "Ann Street, Brisbane, Australia",
        "detail": "Clearway (C11) 7am–11am Monday–Friday (RIGHT); 7am–11am Monday–Saturday (LEFT)",
        "lat": -27.462473,
        "lng": 153.031052,
      },
      {
        "id": "peak4-am-11",
        "order": 11,
        "name": "Leichhardt Street, Spring Hill",
        "query": "Leichhardt Street, Spring Hill QLD, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday between North Street & Little Edward Street",
        "lat": -27.461997,
        "lng": 153.021440,
      },
      {
        "id": "peak4-am-12",
        "order": 12,
        "name": "Wickham Terrace, Spring Hill",
        "query": "Wickham Terrace, Spring Hill QLD, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday between Gregory Terrace & North Street",
        "lat": -27.461130,
        "lng": 153.018917,
      },
      {
        "id": "peak4-am-13",
        "order": 13,
        "name": "Gregory Terrace, Spring Hill",
        "query": "Gregory Terrace, Spring Hill QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Brunswick Street & Warry Street",
        "lat": -27.452789,
        "lng": 153.028791,
      },
      {
        "id": "peak4-am-14",
        "order": 14,
        "name": "Gotha Street, Fortitude Valley",
        "query": "Gotha Street, Fortitude Valley QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Barry Parade & Wickham Street",
        "lat": -27.459090,
        "lng": 153.030983,
      },
      {
        "id": "peak4-am-15",
        "order": 15,
        "name": "Water Street, Spring Hill",
        "query": "Water Street, Spring Hill QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday before Boundary Street intersection",
        "lat": -27.454226,
        "lng": 153.029437,
      }
    ]
  },
  {
    "id": "peak4-pm",
    "name": "Peak 4 – Afternoon",
    "group": "Peak 4",
    "period": "Afternoon",
    "locations": [
      {
        "id": "peak4-pm-01",
        "order": 1,
        "name": "Ann Street, Brisbane",
        "query": "Ann Street, Brisbane, Australia",
        "detail": "Clearway (C11) 2pm–7pm Monday–Friday (RIGHT); 2pm–7pm Monday–Saturday (LEFT)",
        "lat": -27.462473,
        "lng": 153.031052,
      },
      {
        "id": "peak4-pm-02",
        "order": 2,
        "name": "Boundary Street, Spring Hill",
        "query": "Boundary Street, Spring Hill QLD, Australia",
        "detail": "No Stopping (S11) 2pm–6pm Monday–Friday between Milne Street & Gregory Terrace",
        "lat": -27.460212,
        "lng": 153.019934,
      },
      {
        "id": "peak4-pm-03",
        "order": 3,
        "name": "Saint Pauls Terrace, Fortitude Valley / Spring Hill",
        "query": "Saint Pauls Terrace, Fortitude Valley QLD, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday both directions",
        "lat": -27.451965,
        "lng": 153.035799,
      },
      {
        "id": "peak4-pm-04",
        "order": 4,
        "name": "Boundary Street, Spring Hill",
        "query": "Boundary Street, Spring Hill QLD, Australia",
        "detail": "No Stopping (S11) 4pm–6pm Monday–Friday both directions",
        "lat": -27.461629,
        "lng": 153.029604,
      },
      {
        "id": "peak4-pm-05",
        "order": 5,
        "name": "Little Edward Street, Spring Hill",
        "query": "Little Edward Street, Spring Hill QLD, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday",
        "lat": -27.461042,
        "lng": 153.024473,
      },
      {
        "id": "peak4-pm-06",
        "order": 6,
        "name": "Upper Edward Street, Spring Hill",
        "query": "Upper Edward Street, Spring Hill QLD, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday both directions",
        "lat": -27.463022,
        "lng": 153.024388,
      },
      {
        "id": "peak4-pm-07",
        "order": 7,
        "name": "Turbot Street, Spring Hill / Brisbane",
        "query": "Turbot Street, Brisbane, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday",
        "lat": -27.467324,
        "lng": 153.023095,
      },
      {
        "id": "peak4-pm-08",
        "order": 8,
        "name": "Wharf Street, Spring Hill / Brisbane",
        "query": "Wharf Street, Brisbane, Australia",
        "detail": "No Stopping (S11) 2pm–7pm Monday–Friday",
        "lat": -27.463604,
        "lng": 153.028315,
      },
      {
        "id": "peak4-pm-09",
        "order": 9,
        "name": "Wharf Street, Spring Hill / Brisbane",
        "query": "Wharf Street, Brisbane, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday both directions",
        "lat": -27.464494,
        "lng": 153.029182,
      },
      {
        "id": "peak4-pm-10",
        "order": 10,
        "name": "Wharf Street, Spring Hill / Brisbane",
        "query": "Wharf Street, Brisbane, Australia",
        "detail": "No Stopping (S11) 4pm–6pm Monday–Friday",
        "lat": -27.462679,
        "lng": 153.027321,
      },
      {
        "id": "peak4-pm-10",
        "order": 10,
        "name": "Macrossan Street, Brisbane",
        "query": "Macrossan Street, Brisbane, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday",
        "lat": -27.462891,
        "lng": 153.032395,
      },
      {
        "id": "peak4-pm-11",
        "order": 11,
        "name": "Adelaide Street, Brisbane",
        "query": "Adelaide Street, Brisbane, Australia",
        "detail": "Clearway (C11) & No Stopping (S11) 4pm–7pm Monday–Friday between Wharf Street & Boundary Street",
        "lat": -27.462893,
        "lng": 153.031893,
      },
      {
        "id": "peak4-pm-12",
        "order": 12,
        "name": "Leichhardt Street, Spring Hill",
        "query": "Leichhardt Street, Spring Hill QLD, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday between Little Edward Street & Wickham Terrace",
        "lat": -27.462290,
        "lng": 153.023204,
      },
      {
        "id": "peak4-pm-13",
        "order": 13,
        "name": "Wickham Terrace, Spring Hill",
        "query": "Wickham Terrace, Spring Hill QLD, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday between Leichhardt Street & Parkland Blvd",
        "lat": -27.461749,
        "lng": 153.020382,
      },
      {
        "id": "peak4-pm-14",
        "order": 14,
        "name": "Gregory Terrace, Spring Hill",
        "query": "Gregory Terrace, Spring Hill QLD, Australia",
        "detail": "No Stopping (S11) 4pm–6pm Monday–Friday between Brunswick Street & Warry Street",
        "lat": -27.452789,
        "lng": 153.028791,
      }
    ]
  },
  {
    "id": "peak5-am",
    "name": "Peak 5 – Morning",
    "group": "Peak 5",
    "period": "Morning",
    "locations": [
      {
        "id": "peak5-am-01",
        "order": 1,
        "name": "Wickham Street, Fortitude Valley",
        "query": "Wickham Street, Fortitude Valley QLD, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-am-02",
        "order": 2,
        "name": "Constance Street, Fortitude Valley",
        "query": "Constance Street, Fortitude Valley QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Wickham Street & Ann Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-am-03",
        "order": 3,
        "name": "McLachlan Street, Fortitude Valley",
        "query": "McLachlan Street, Fortitude Valley QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Connor Street & James Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-am-04",
        "order": 4,
        "name": "Brookes Street, Fortitude Valley / Bowen Hills",
        "query": "Brookes Street, Bowen Hills QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-am-05",
        "order": 5,
        "name": "O'Connell Terrace, Bowen Hills",
        "query": "O'Connell Terrace, Bowen Hills QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-am-06",
        "order": 6,
        "name": "Abbortsford Road, Bowen Hills",
        "query": "Abbortsford Road, Bowen Hills QLD, Australia",
        "detail": "No Stopping (S11) & Clearway (C11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-am-07",
        "order": 7,
        "name": "Edmondstone Road, Bowen Hills",
        "query": "Edmondstone Road, Bowen Hills QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday before Abbortsford Road intersection",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-am-08",
        "order": 8,
        "name": "Montplier Road, Bowen Hills",
        "query": "Montplier Road, Bowen Hills QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Down Street & Dukinfield Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-am-09",
        "order": 9,
        "name": "Brunswick Street, Fortitude Valley / New Farm",
        "query": "Brunswick Street, Fortitude Valley QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Barker Street & Malt Street",
        "lat": null,
        "lng": null,
      }
    ]
  },
  {
    "id": "peak5-pm",
    "name": "Peak 5 – Afternoon",
    "group": "Peak 5",
    "period": "Afternoon",
    "locations": [
      {
        "id": "peak5-pm-01",
        "order": 1,
        "name": "Wickham Street, Fortitude Valley",
        "query": "Wickham Street, Fortitude Valley QLD, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-pm-02",
        "order": 2,
        "name": "Constance Street, Fortitude Valley",
        "query": "Constance Street, Fortitude Valley QLD, Australia",
        "detail": "No Stopping (S11) 4pm–6pm Monday–Friday between Wickham Street & Ann Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-pm-03",
        "order": 3,
        "name": "McLachlan Street, Fortitude Valley",
        "query": "McLachlan Street, Fortitude Valley QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday between Connor Street & James Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-pm-04",
        "order": 4,
        "name": "Brookes Street, Fortitude Valley / Bowen Hills",
        "query": "Brookes Street, Bowen Hills QLD, Australia",
        "detail": "No Stopping (S11) 4pm–6pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-pm-05",
        "order": 5,
        "name": "O'Connell Terrace, Bowen Hills",
        "query": "O'Connell Terrace, Bowen Hills QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-pm-06",
        "order": 6,
        "name": "Abbortsford Road, Bowen Hills",
        "query": "Abbortsford Road, Bowen Hills QLD, Australia",
        "detail": "Inbound No Stopping (S11) 4pm–6pm; outbound Clearway (C11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-pm-07",
        "order": 7,
        "name": "Edmondstone Road, Bowen Hills",
        "query": "Edmondstone Road, Bowen Hills QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday before Abbortsford Road intersection",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-pm-08",
        "order": 8,
        "name": "Montplier Road, Bowen Hills",
        "query": "Montplier Road, Bowen Hills QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday between Down Street & Dukinfield Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-pm-09",
        "order": 9,
        "name": "Brunswick Street, Fortitude Valley / New Farm",
        "query": "Brunswick Street, Fortitude Valley QLD, Australia",
        "detail": "No Stopping (S11) 4pm–6pm Monday–Friday between Arthur Street & Annie Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-pm-10",
        "order": 10,
        "name": "Warner Street, Fortitude Valley",
        "query": "Warner Street, Fortitude Valley QLD, Australia",
        "detail": "Bus Zone (B11) 4pm–7pm Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak5-pm-11",
        "order": 11,
        "name": "Commercial Road, Newstead",
        "query": "Commercial Road, Newstead QLD, Australia",
        "detail": "No Stopping (S11) 4pm–6pm Monday–Friday between Leopold Street & Ann Street",
        "lat": null,
        "lng": null,
      }
    ]
  },
  {
    "id": "peak6-am",
    "name": "Peak 6 – Morning",
    "group": "Peak 6",
    "period": "Morning",
    "locations": [
      {
        "id": "peak6-am-01",
        "order": 1,
        "name": "Cordelia Street, South Brisbane",
        "query": "Cordelia Street, South Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday",
        "lat": -27.481139,
        "lng": 153.019427,
      },
      {
        "id": "peak6-am-02",
        "order": 2,
        "name": "Marivale Street, South Brisbane",
        "query": "Marivale Street, South Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday",
        "lat": -27.472504,
        "lng": 153.014705,
      },
      {
        "id": "peak6-am-03",
        "order": 3,
        "name": "Marivale Street, South Brisbane",
        "query": "Marivale Street, South Brisbane QLD, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday",
        "lat": -27.475166,
        "lng": 153.016552,
      },
      {
        "id": "peak6-am-04",
        "order": 4,
        "name": "Glenelg Street, South Brisbane",
        "query": "Glenelg Street, South Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday",
        "lat": -27.478576,
        "lng": 153.018744,
      },
      {
        "id": "peak6-am-05",
        "order": 5,
        "name": "Montegue Road, South Brisbane",
        "query": "Montegue Road, South Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Beesley Street & Jane Street",
        "lat": null,
        "lng": null,
      }
    ]
  },
  {
    "id": "peak6-pm",
    "name": "Peak 6 – Afternoon",
    "group": "Peak 6",
    "period": "Afternoon",
    "locations": [
      {
        "id": "peak6-pm-01",
        "order": 1,
        "name": "Cordelia Street, South Brisbane",
        "query": "Cordelia Street, South Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday between Vulture Street & Ernest Street",
        "lat": -27.481139,
        "lng": 153.019427,
      },
      {
        "id": "peak6-pm-02",
        "order": 2,
        "name": "Cordelia Street, South Brisbane",
        "query": "Cordelia Street, South Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 4pm–6pm between Melbourne Street & Peel Street",
        "lat": -27.475383,
        "lng": 153.015365,
      },
      {
        "id": "peak6-pm-03",
        "order": 3,
        "name": "Marivale Street, South Brisbane",
        "query": "Marivale Street, South Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 4pm–6pm Monday–Friday between Montegue Road & Peel Street",
        "lat": -27.472504,
        "lng": 153.014705,
      },
      {
        "id": "peak6-pm-04",
        "order": 4,
        "name": "Marivale Street, South Brisbane",
        "query": "Marivale Street, South Brisbane QLD, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday between Melbourne Street & Glenelg Street",
        "lat": -27.475166,
        "lng": 153.016552,
      },
      {
        "id": "peak6-pm-05",
        "order": 5,
        "name": "Glenelg Street, South Brisbane",
        "query": "Glenelg Street, South Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday",
        "lat": -27.478576,
        "lng": 153.018744,
      },
      {
        "id": "peak6-pm-06",
        "order": 6,
        "name": "Montegue Road, South Brisbane",
        "query": "Montegue Road, South Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 4pm–6pm Monday–Friday between Beesley Street & Jane Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak6-pm-07",
        "order": 7,
        "name": "Fleet Lane, South Brisbane",
        "query": "Fleet Lane, South Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 4pm–6pm Monday–Friday",
        "lat": -27.472330,
        "lng": 153.016637,
      }
    ]
  },
  {
    "id": "peak7-am",
    "name": "Peak 7 – Morning",
    "group": "Peak 7",
    "period": "Morning",
    "locations": [
      {
        "id": "peak7-am-01",
        "order": 1,
        "name": "Stanley Street, East Brisbane",
        "query": "Stanley Street, East Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 6am–9am Monday–Friday between Norman Street & Wellington Road",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak7-am-02",
        "order": 2,
        "name": "Annerley Road, Woolloongabba / South Brisbane",
        "query": "Annerley Road, Woolloongabba QLD, Australia",
        "detail": "No Stopping (S11) 6am–9am Monday–Friday between Stephens Road & Stanley Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak7-am-03",
        "order": 3,
        "name": "Ipswich Road, Woolloongabba",
        "query": "Ipswich Road, Woolloongabba QLD, Australia",
        "detail": "Clearway (C11) 7am–9am Monday–Friday between Stanley Street & Balaclava Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak7-am-04",
        "order": 4,
        "name": "Balaclava Street, Woolloongabba",
        "query": "Balaclava Street, Woolloongabba QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak7-am-05",
        "order": 5,
        "name": "Logan Road, Woolloongabba",
        "query": "Logan Road, Woolloongabba QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday between Qualtrough Street & Balaclava Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak7-am-06",
        "order": 6,
        "name": "Wellington Road, East Brisbane",
        "query": "Wellington Road, East Brisbane QLD, Australia",
        "detail": "Clearway (C11) 7am–10am Monday–Friday between Vulture Street & Shafston Avenue",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak7-am-07",
        "order": 7,
        "name": "Okeefe Street, Woolloongabba",
        "query": "Okeefe Street, Woolloongabba QLD, Australia",
        "detail": "No Stopping (S11) 7am–9am Monday–Friday after Ipswich Road intersection",
        "lat": null,
        "lng": null,
      }
    ]
  },
  {
    "id": "peak7-pm",
    "name": "Peak 7 – Afternoon",
    "group": "Peak 7",
    "period": "Afternoon",
    "locations": [
      {
        "id": "peak7-pm-01",
        "order": 1,
        "name": "Annerley Road, Woolloongabba / South Brisbane",
        "query": "Annerley Road, Woolloongabba QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday between Stephens Road & Stanley Street",
        "lat": null,
        "lng": null,
      },
      {
        "id": "peak7-pm-02",
        "order": 2,
        "name": "Vulture Street, South Brisbane",
        "query": "Vulture Street, South Brisbane QLD, Australia",
        "detail": "Clearway (C11) 4pm–7pm Monday–Friday between Dock Street & Leopard Street",
        "lat": -27.483109,
        "lng": 153.026774,
      },
      {
        "id": "peak7-pm-03",
        "order": 3,
        "name": "Ipswich Road, Woolloongabba",
        "query": "Ipswich Road, Woolloongabba QLD, Australia",
        "detail": "Clearway (C11) 4pm–6pm Monday–Friday between Stanley Street & Balaclava Street",
        "lat": -27.487010,
        "lng": 153.036063,
      },
      {
        "id": "peak7-pm-04",
        "order": 4,
        "name": "Balaclava Street, Woolloongabba",
        "query": "Balaclava Street, Woolloongabba QLD, Australia",
        "detail": "No Stopping (S11) 4pm–6pm Monday–Friday",
        "lat": -27.490326,
        "lng": 153.038124,
      },
      {
        "id": "peak7-pm-05",
        "order": 5,
        "name": "Logan Road, Woolloongabba",
        "query": "Logan Road, Woolloongabba QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday between Lotus Street & Deshon Street",
        "lat": -27.490705,
        "lng": 153.040141,
      },
      {
        "id": "peak7-pm-06",
        "order": 6,
        "name": "Overend Street, East Brisbane",
        "query": "Overend Street, East Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 4pm–6pm Monday–Friday between Lisburn Street & Hampton Street",
        "lat": -27.488538,
        "lng": 153.041429,
      }, {
        "id": "peak7-pm-07",
        "order": 7,
        "name": "Overend Street, East Brisbane",
        "query": "Overend Street, East Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday between Hampton Street & Wellington Road",
        "lat": -27.488334,
        "lng": 153.040591,
      },
      {
        "id": "peak7-pm-08",
        "order": 8,
        "name": "Wellington Road, East Brisbane",
        "query": "Wellington Road, East Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 4pm–6pm between Overend Street & Logan Road",
        "lat": -27.489130,
        "lng": 153.039469,
      },{
        "id": "peak7-pm-09",
        "order": 9,
        "name": "Wellington Road, East Brisbane",
        "query": "Wellington Road, East Brisbane QLD, Australia",
        "detail": "Clearway (C11) 4pm–7pm between Waterloo Street & Lytton Road",
        "lat": -27.480914,
        "lng": 153.041052,
      },
      {
        "id": "peak7-pm-10",
        "order": 10,
        "name": "Water Street, South Brisbane",
        "query": "Water Street, South Brisbane QLD, Australia",
        "detail": "No Stopping (S11) 4pm–7pm Monday–Friday",
        "lat": -27.484542,
        "lng": 153.029116,
      },
      {
        "id": "peak7-pm-11",
        "order": 11,
        "name": "Okeefe Street, Woolloongabba",
        "query": "Okeefe Street, Woolloongabba QLD, Australia",
        "detail": "No Stopping (S11) 3pm–7pm Monday–Friday after Ipswich Road intersection",
        "lat": null,
        "lng": null,
      }
    ]
  }
];
